services:
  github-runner:
    build:
      context: ./
      dockerfile: Dockerfile.arm64
    image: ghcr.io/quantcdn-templates/app-github-actions-runner:arm64
    restart: unless-stopped
    environment:
      # Required: GitHub organization/user name
      - GITHUB_ORG=${GITHUB_ORG}
      
      # Required: GitHub runner registration token
      # Get from: https://github.com/{ORG}/settings/actions/runners/new
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      
      # Optional: Custom runner name (defaults to hostname)
      - RUNNER_NAME=${RUNNER_NAME:-quant-cloud-runner-arm64}
      
      # Optional: Custom labels (defaults to quant-cloud,self-hosted)
      - RUNNER_LABELS=${RUNNER_LABELS:-quant-cloud,self-hosted,ARM64}
      
      # Optional: Working directory for actions
      - RUNNER_WORK_DIR=${RUNNER_WORK_DIR:-_work}
    
    # Mount Docker socket to allow Docker-in-Docker for actions that need it
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_work:/home/actions-runner/_work
    
    # Resources (adjust based on your needs)
    # mem_limit: 2g
    # cpus: 1.0

volumes:
  runner_work: