services:
  buildkit:
    image: moby/buildkit:latest
    restart: unless-stopped
    environment:
      - BUILDKITD_FLAGS=--oci-worker-no-process-sandbox --addr tcp://0.0.0.0:1234
    # No shared cache volume - each instance uses ephemeral storage to avoid lock conflicts

  github-runner:
    build:
      context: ./
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    image: ghcr.io/quantcdn-templates/app-github-actions-runner:arm64
    restart: unless-stopped
    depends_on:
      - buildkit
    environment:
      # Required: GitHub organization/user name
      - GITHUB_ORG=${GITHUB_ORG}
      
      # Auth: Use either GITHUB_TOKEN (registration token) or GITHUB_PAT (preferred)
      # GITHUB_TOKEN: Short-lived registration token from: https://github.com/{ORG}/settings/actions/runners/new  
      # GITHUB_PAT: Long-lived Personal Access Token (preferred for automation)
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_PAT=${GITHUB_PAT}
      
      # Optional: Custom runner name (defaults to QUANT_APP_NAME + random suffix)
      - RUNNER_NAME=${RUNNER_NAME}
      - QUANT_APP_NAME=${QUANT_APP_NAME}
      
      # Optional: Custom labels (defaults to quant-cloud,self-hosted)docker 
      - RUNNER_LABELS=${RUNNER_LABELS:-quant-cloud,self-hosted,ARM64}
      
      # Optional: Working directory for actions
      - RUNNER_WORK_DIR=${RUNNER_WORK_DIR:-_work}
      
      # Number of parallel runners (default: 1)
      # Examples: 2vCPU/4GB→2 runners, 4vCPU/8GB→4 runners, 8vCPU/16GB→6 runners
      - RUNNER_COUNT=${RUNNER_COUNT:-1}
      
      # BuildKit configuration for ECS scaling compatibility
      - BUILDKIT_HOST=tcp://buildkit:1234
      
      # Allow runner to run as root user
      - RUNNER_ALLOW_RUNASROOT=1
    
    # Fargate-compatible volumes (only config needs persistence)
    volumes:
      - runner_config:/runner/.runner-config
      # _work uses ephemeral storage - EFS doesn't support tar ownership changes
    
    # Resources (adjust based on your needs)
    # mem_limit: 2g
    # cpus: 1.0

volumes:
  runner_config: