services:
  buildkit:
    image: moby/buildkit:latest
    restart: unless-stopped
    environment:
      - BUILDKITD_FLAGS=--oci-worker-no-process-sandbox --addr tcp://0.0.0.0:1234
    volumes:
      - buildkit-cache:/var/lib/buildkit

  github-runner:
    build:
      context: ./
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: ghcr.io/quantcdn-templates/app-github-actions-runner:latest
    restart: unless-stopped
    depends_on:
      - buildkit
    environment:
      # Required: GitHub organization/user name
      - GITHUB_ORG=${GITHUB_ORG}
      
      # Required for initial registration only (persisted after first run)
      # Get from: https://github.com/{ORG}/settings/actions/runners/new
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      
      # Optional: Custom runner name (defaults to QUANT_APP_NAME + random suffix)
      - RUNNER_NAME=${RUNNER_NAME}
      - QUANT_APP_NAME=${QUANT_APP_NAME}
      
      # Optional: Custom labels (defaults to quant-cloud,self-hosted)
      - RUNNER_LABELS=${RUNNER_LABELS:-quant-cloud,self-hosted}
      
      # Optional: Working directory for actions
      - RUNNER_WORK_DIR=${RUNNER_WORK_DIR:-_work}
      
      # BuildKit configuration for ECS scaling compatibility
      - BUILDKIT_HOST=tcp://buildkit:1234
    
    # Fargate-compatible volumes
    volumes:
      - runner_config:/runner/.runner-config
      - runner_work:/runner/_work
    
    # Resources (adjust based on your needs)
    # mem_limit: 2g
    # cpus: 1.0

volumes:
  buildkit-cache:
  runner_config:
  runner_work: